<?php
/**
* 2007-2016 PrestaShop
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@prestashop.com so we can send you a copy immediately.
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade PrestaShop to newer
* versions in the future. If you wish to customize PrestaShop for your
* needs please refer to http://www.prestashop.com for more information.
*
*  @author    PrestaShop SA <contact@prestashop.com>
*  @copyright 2007-2016 PrestaShop SA
*  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*/

class SampleDataSlider
{
	public function initData()
	{
		$return = true;
		$languages = Language::getLanguages(true);
		$id_shop = Configuration::get('PS_SHOP_DEFAULT');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow` (`id_wtslideshow`, `position`, `slidedelay`, `transition2d`, `transition3d`, `timeshift`, `active`) VALUES 
		(1, 0, 4000, \'["1"]\', "false", 0, 1),
		(2, 0, 4000, \'["2"]\', "false", 0, 1),
		(3, 0, 4000, \'["3"]\', "false", 0, 1);
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_shop` (`id_wtslideshow`, `id_shop`, `position`, `slidedelay`, `transition2d`, `transition3d`, `timeshift`, `active`) VALUES 
		(1, "'.$id_shop.'", 0, 4000, \'["1"]\', "false", 0, 1),
		(2, "'.$id_shop.'", 0, 4000, \'["2"]\', "false", 0, 1),
		(3, "'.$id_shop.'", 0, 4000, \'["3"]\', "false", 0, 1);
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_options` (`id_wtslideshow_op`, `options`) VALUES 
		(1, \'{"fullwidth":"true","width":"1920","height":"850","responsive":"true","responsiveUnder":"1920","layersContainer":"1920","showmobile":"true","autoStart":"true","pauseOnHover":"true","firstSlide":"1","animateFirstSlide":"true","loops":"0","forceLoopNum":"true","towWaySlideshow":"false","randomSlideshow":"true","skin":"v5","skinsPath":"views\/css\/skins\/","globalBGColor":"transparent","globalBGImage":"false","navPrevNext":"true","navStartStop":"false","navButtons":"true","hoverPrevNext":"true","hoverBottomNav":"true","keybNav":"true","touchNav":"true","showBarTimer":"false","showCircleTimer":"false","thumbnailNavigation":"hover","tnContainerWidth":"60%","tnWidth":"100","tnHeight":"60","tnActiveOpacity":"35","tnInactiveOpacity":"100","autoPlayVideos":"true","autoPauseSlideshow":"auto","youtubePreview":"maxresdefault.jpg","imgPreload":"true","lazyLoad":"true","yourLogo":"false","yourLogoStyle":"left: -10px; top: -10px;","yourLogoLink":"false","yourLogoTarget":"_blank"}\')
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_options_shop` (`id_wtslideshow_op`, `id_shop`, `options`) VALUES 
		(1, "'.$id_shop.'", \'{"fullwidth":"false","width":"1920","height":"850","responsive":"true","responsiveUnder":"1920","layersContainer":"1920","showmobile":"true","autoStart":"true","pauseOnHover":"true","firstSlide":"1","animateFirstSlide":"true","loops":"0","forceLoopNum":"true","towWaySlideshow":"false","randomSlideshow":"true","skin":"v5","skinsPath":"views\/css\/skins\/","globalBGColor":"transparent","globalBGImage":"false","navPrevNext":"true","navStartStop":"false","navButtons":"true","hoverPrevNext":"true","hoverBottomNav":"true","keybNav":"true","touchNav":"true","showBarTimer":"false","showCircleTimer":"false","thumbnailNavigation":"hover","tnContainerWidth":"60%","tnWidth":"100","tnHeight":"60","tnActiveOpacity":"35","tnInactiveOpacity":"100","autoPlayVideos":"true","autoPauseSlideshow":"auto","youtubePreview":"maxresdefault.jpg","imgPreload":"true","lazyLoad":"true","yourLogo":"false","yourLogoStyle":"left: -10px; top: -10px;","yourLogoLink":"false","yourLogoTarget":"_blank"}\')
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_caption` (`id_caption`, `id_wtslideshow`, `type`, `order`, `params`) VALUES 
		(10, 1, 1, 300, \'{"style":"big_black","parallaxlevel":"0","class":"","datax":"175","datay":"366","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(11, 1, 1, 600, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"336","datay":"439","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(12, 1, 1, 900, \'{"style":"big_bluee","parallaxlevel":"0","class":"","datax":"109","datay":"498","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(13, 1, 1, 1200, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"397","datay":"612","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		
		(14, 2, 1, 300, \'{"style":"big_orange","parallaxlevel":"0","class":"","datax":"188","datay":"297","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),		
		(15, 2, 1, 900, \'{"style":"big_bluee","parallaxlevel":"0","class":"","datax":"146","datay":"403","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(16, 2, 1, 1500, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"447","datay":"544","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(17, 2, 2, 300, \'{"style":"big_black","parallaxlevel":"2","class":"","datax":"885","datay":"110","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		
		(18, 3, 2, 300, \'{"style":"big_black","parallaxlevel":"2","class":"","datax":"231","datay":"43","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(19, 3, 1, 600, \'{"style":"very_big_white","parallaxlevel":"0","class":"","datax":"1211","datay":"186","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(20, 3, 1, 900, \'{"style":"very_big_white","parallaxlevel":"0","class":"big","datax":"1133","datay":"462","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(21, 3, 1, 900, \'{"style":"very_large_text","parallaxlevel":"0","class":"","datax":"1196","datay":"291","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(22, 3, 1, 1200, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"1271","datay":"610","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\');');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_caption_shop` (`id_caption`, `id_wtslideshow`, `id_shop`, `type`, `order`, `params`) VALUES 
		(10, 1, "'.$id_shop.'", 1, 300, \'{"style":"big_black","parallaxlevel":"0","class":"","datax":"175","datay":"366","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(11, 1, "'.$id_shop.'", 1, 600, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"336","datay":"439","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(12, 1, "'.$id_shop.'", 1, 900, \'{"style":"big_bluee","parallaxlevel":"0","class":"","datax":"109","datay":"498","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(13, 1, "'.$id_shop.'", 1, 1200, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"397","datay":"612","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		
		(14, 2, "'.$id_shop.'", 1, 300, \'{"style":"big_orange","parallaxlevel":"0","class":"","datax":"188","datay":"297","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),		
		(15, 2, "'.$id_shop.'", 1, 600, \'{"style":"big_bluee","parallaxlevel":"0","class":"","datax":"146","datay":"403","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(16, 2, "'.$id_shop.'", 1, 900, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"447","datay":"544","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(17, 2, "'.$id_shop.'", 2, 600, \'{"style":"big_black","parallaxlevel":"2","class":"","datax":"885","datay":"110","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		
		(18, 3, "'.$id_shop.'", 2, 300, \'{"style":"big_black","parallaxlevel":"2","class":"","datax":"231","datay":"43","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(19, 3, "'.$id_shop.'", 1, 600, \'{"style":"very_big_white","parallaxlevel":"0","class":"","datax":"1211","datay":"186","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(20, 3, "'.$id_shop.'", 1, 900, \'{"style":"very_big_white","parallaxlevel":"0","class":"big","datax":"1133","datay":"462","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(21, 3, "'.$id_shop.'", 1, 900, \'{"style":"very_large_text","parallaxlevel":"0","class":"","datax":"1196","datay":"291","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(22, 3, "'.$id_shop.'", 1, 1200, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"1271","datay":"610","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\');');
		
		
		foreach ($languages as $language)
		{
			$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_lang` (`id_wtslideshow`, `id_lang`, `id_shop`, `title`, `url`, `image`, `thumbnail`) VALUES 
			(1, "'.$language['id_lang'].'", "'.$id_shop.'", "Slider title", "#", "27a08d2f061023d13264004734a6cc0c35887e57_slider1.jpg", ""),
			(2, "'.$language['id_lang'].'", "'.$id_shop.'", "Slider title", "#", "fe4bc8f25a2f4ed9bdf2f232904df4b4de5df3fe_slide2.jpg", ""),
			(3, "'.$language['id_lang'].'", "'.$id_shop.'", "Slider title", "#", "cb3df3780a4780bfdf52f5f1f4f6d5f28a166d61_silde3.jpg", "");
			');
			
			$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_caption_lang` (`id_caption`, `id_shop`, `id_lang`, `captext`, `capimage`, `capvideo`, `link`) VALUES 
			(10, "'.$id_shop.'", "'.$language['id_lang'].'", "umi hammer", "Layer Image 0", "Layer Video 0", "#"),
			(11, "'.$id_shop.'", "'.$language['id_lang'].'", "4g smartphone with 64bit", "Layer Image 1", "Layer Video 1", "#"),
			(12, "'.$id_shop.'", "'.$language['id_lang'].'", "Lorem Ipsum is simply dummy text of a, used in the presentation and layout for print serving Lorem Ipsum is simply dummy text of a, used in the presentation", "Layer Image 2", "Layer Video 2", "#"),
			(13, "'.$id_shop.'", "'.$language['id_lang'].'", "view more", "Layer Image 3", "Layer Video 3", "#"),
			
			(14, "'.$id_shop.'", "'.$language['id_lang'].'", "xbox-360", "Layer Image 0", "Layer Video 0", "#"),
			(15, "'.$id_shop.'", "'.$language['id_lang'].'", "Lorem Ipsum is simply dummy text of a, used in the presentation and layout for print serving Lorem Ipsum is simply dummy text of a, used in the presentation", "Layer Image 1", "Layer Video 1", "#"),
			(16, "'.$id_shop.'", "'.$language['id_lang'].'", "view more", "Layer Image 2", "Layer Video 2", "#"),
			(17, "'.$id_shop.'", "'.$language['id_lang'].'", "image caption", "a4945948b01210771c52dea039163fb7667e2e37_slide3.png", "", "#"),
			
			(18, "'.$id_shop.'", "'.$language['id_lang'].'", "image caption", "2cda5c83432a2439c49b7342a58324f1020628da_slide2.png", "", "#"),
			(19, "'.$id_shop.'", "'.$language['id_lang'].'", "hear the truth", "Layer Image 1", "Layer Video 1", "#"),
			(20, "'.$id_shop.'", "'.$language['id_lang'].'", "sound you can see", "Layer Image 2", "Layer Video 2", "#"),
			(21, "'.$id_shop.'", "'.$language['id_lang'].'", "JBL", "Layer Image 3", "Layer Video 3", "#"),
			(22, "'.$id_shop.'", "'.$language['id_lang'].'", "view  more", "Layer Image 4", "Layer Video 4", "#");');
		}
		return $return;
	}
}
?>