<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3oqkf75\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3oqkf75/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3oqkf75.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3oqkf75\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3oqkf75\appProdProjectContainer([
    'container.build_hash' => '3oqkf75',
    'container.build_id' => '7272f013',
    'container.build_time' => 1579806112,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3oqkf75');
