<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZlfzvaf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZlfzvaf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZlfzvaf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZlfzvaf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZlfzvaf\appDevDebugProjectContainer([
    'container.build_hash' => 'Zlfzvaf',
    'container.build_id' => 'ce18e465',
    'container.build_time' => 1585219660,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZlfzvaf');
